### ISSUE TITLE
取证方向开发

### ISSUE THREAD

**Issue by haropng** [SteveZMTstudios/AppBackup-onRecovery#1]
[zh-CN]
可以引入数据分析匹配吗
• 解析数据库，匹配应用活动数据
• 桌面端ai数据分析

**Comment by SteveZMTstudios** [comment]
1.本项目是为解锁bootloader用户在无法访问系统时紧急备份设备的程序数据，需要先对data分区解密才可操作。

~~2.能做，得加钱（~~
